version: '3.8'

services:
  finxpert-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: finxpert-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
